---
- name: About to install apachetomcat
  hosts: tomcat-server
  gather_facts: True
  become: yes
#  vars_prompt:
#    name: "hosts"
#    prompt: " What is the host IP? example 192.16.0.xxx"
#    private: no
  vars:
    password: $1$p85kRNB8$2q/bDJJzFXZ92tYsQ310K.
  
  tasks:
  - name: Installing java jdk
    yum:
      name: ['java-1.8.0-openjdk-devel','wget']            
      state: present
    when: ansible_distribution == "CentOS"
    
  - name: Creating a directory for tomcat
    file:
      path: /opt/tomcat
      owner: tomcat
      mode: 0775
      state: directory
      recurse: yes
    ignore_errors: yes  
    
  - name: Creating tomcat group
    group:
      name: tomcat
      state: present
      
  - name: Creating tomcat user
    user:
      name: tomcat
      shell: /bin/bash
      groups: tomcat
      append: no
      password: "{{ password }}"
    
  - name: Downloading Tomcat 8 archive
    get_url:
      url: http://mirrors.koehn.com/apache/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz
      dest: /opt/tomcat 
      mode: 0775
    ignore_errors: yes  
      
  - name: Extracting apache-tomcat tar.gz
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.19.tar.gz
      dest: /opt/tomcat/
      remote_src: yes
    ignore_errors: yes
    
  - name: Renaming apache-tomcat-9.0.19
    command: mv /opt/tomcat/apache-tomcat-9.0.19 /opt/tomcat/tomcat9
    when: True
    
#  - name: Configuring CATALINA_HOME
#    shell: "{{ item }}"
#    with_items:
#      - echo "export CATALINA_HOME="/opt/tomcat/tomcat9"" >> ~/.bashrc
#      - source ~/.bashrc
 #   ignore_errors: yes  
      
  - name: starting apachetomcat service
    shell: cd /opt/tomcat/tomcat9 ./bin/startup.sh 
    ignore_errors: yes  
      
  - name: Opening ports 8080
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
 
  - name: Reloading firewalld service
    command: firewall-cmd --reload
