---
- name: About to install apachetomcat
  hosts: najite
  gather_facts: True
  become: yes
#  vars_prompt:
#    name: "hosts"
#    prompt: " What is the host IP? example 192.16.0.xxx"
#    private: no
  vars:
    password: $1$p85kRNB8$2q/bDJJzFXZ92tYsQ310K.
  
  tasks:
  - name: Installing java jdk
    yum:
      name: ['java-1.7.0-openjdk-devel','wget']            
      state: present
    when: ansible_distribution == "CentOS"
    
  - name: Creating a directory for tomcat
    file:
      path: /opt/tomcat
      owner: tomcat
      mode: 0775
      state: directory
      recurse: yes
    
  - name: Creating tomcat group
    group:
      name: tomcat
      state: present
      
  - name: Creating tomcat user
    user:
      name: tomcat
      shell: /bin/bash
      groups: tomcat
      append: yes
      password: "{{ password }}"
    
  - name: Downloading Tomcat 8 archive
    get_url:
      url: http://mirrors.koehn.com/apache/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz
      dest: /opt/tomcat 
      mode: 0775
    ignore_errors: yes  
      
  - name: Extracting apache-tomcat tar.gz
    unarchive:     #cd /opt/tomcat tar -xf apache-tomcat-9.0.19.tar.gz
      src: /opt/tomcat/apache-tomcat-9.0.19.tar.gz
      dest: /opt/tomcat/
      extra_opts: [--strip-components=1]
      remote_src: yes
    ignore_errors: yes  
      
  - name: starting apachetomcat service
    systemd:
      name: tomcat
      state: started
      enabled: yes
      
  - name: Opening ports 8080
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
